name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.1"
      - name: Install dependencies
        run: poetry install
      - name: Lint & type-check
        run: |
          poetry run ruff .
          poetry run black --check .
          poetry run mypy carioca
      - name: Tests
        run: poetry run pytest --cov=carioca -q
